apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-g1zzm
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2018-02-18T22:46:05Z
    name: builder
    namespace: tasks-dev
    resourceVersion: "32635"
    selfLink: /api/v1/namespaces/tasks-dev/serviceaccounts/builder
    uid: 809e86b7-14fd-11e8-83f6-16444eb360d2
  secrets:
  - name: builder-token-9850m
  - name: builder-dockercfg-g1zzm
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-80w24
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2018-02-18T22:46:05Z
    name: default
    namespace: tasks-dev
    resourceVersion: "32636"
    selfLink: /api/v1/namespaces/tasks-dev/serviceaccounts/default
    uid: 809e0107-14fd-11e8-83f6-16444eb360d2
  secrets:
  - name: default-dockercfg-80w24
  - name: default-token-vxqcj
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-z2l1v
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2018-02-18T22:46:05Z
    name: deployer
    namespace: tasks-dev
    resourceVersion: "32637"
    selfLink: /api/v1/namespaces/tasks-dev/serviceaccounts/deployer
    uid: 809f1b72-14fd-11e8-83f6-16444eb360d2
  secrets:
  - name: deployer-token-b15bw
  - name: deployer-dockercfg-z2l1v
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
